export interface GalleryImage {
  src: string;
  thumb: string;
  width: number;
  height: number;
}

export interface Gallery {
  slug: string;
  title: string;
  images: GalleryImage[];
}

export const galleries: Gallery[] = [
  {
    slug: "passers-by",
    title: "Passers by",
    images: [
      { src: "/images/photography/passers-by/001.webp", thumb: "/images/photography/passers-by/001_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/002.webp", thumb: "/images/photography/passers-by/002_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/003.webp", thumb: "/images/photography/passers-by/003_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/004.webp", thumb: "/images/photography/passers-by/004_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/005.webp", thumb: "/images/photography/passers-by/005_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/006.webp", thumb: "/images/photography/passers-by/006_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/007.webp", thumb: "/images/photography/passers-by/007_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/008.webp", thumb: "/images/photography/passers-by/008_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/009.webp", thumb: "/images/photography/passers-by/009_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/010.webp", thumb: "/images/photography/passers-by/010_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/011.webp", thumb: "/images/photography/passers-by/011_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/012.webp", thumb: "/images/photography/passers-by/012_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/013.webp", thumb: "/images/photography/passers-by/013_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/014.webp", thumb: "/images/photography/passers-by/014_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/015.webp", thumb: "/images/photography/passers-by/015_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/016.webp", thumb: "/images/photography/passers-by/016_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/017.webp", thumb: "/images/photography/passers-by/017_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/018.webp", thumb: "/images/photography/passers-by/018_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/019.webp", thumb: "/images/photography/passers-by/019_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/020.webp", thumb: "/images/photography/passers-by/020_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/021.webp", thumb: "/images/photography/passers-by/021_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/022.webp", thumb: "/images/photography/passers-by/022_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/023.webp", thumb: "/images/photography/passers-by/023_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/024.webp", thumb: "/images/photography/passers-by/024_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/025.webp", thumb: "/images/photography/passers-by/025_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/026.webp", thumb: "/images/photography/passers-by/026_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/027.webp", thumb: "/images/photography/passers-by/027_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/028.webp", thumb: "/images/photography/passers-by/028_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/029.webp", thumb: "/images/photography/passers-by/029_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/030.webp", thumb: "/images/photography/passers-by/030_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/031.webp", thumb: "/images/photography/passers-by/031_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/032.webp", thumb: "/images/photography/passers-by/032_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/033.webp", thumb: "/images/photography/passers-by/033_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/034.webp", thumb: "/images/photography/passers-by/034_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/035.webp", thumb: "/images/photography/passers-by/035_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/036.webp", thumb: "/images/photography/passers-by/036_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/037.webp", thumb: "/images/photography/passers-by/037_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/038.webp", thumb: "/images/photography/passers-by/038_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/039.webp", thumb: "/images/photography/passers-by/039_thumb.webp", width: 1200, height: 1800 },
      { src: "/images/photography/passers-by/040.webp", thumb: "/images/photography/passers-by/040_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/041.webp", thumb: "/images/photography/passers-by/041_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/042.webp", thumb: "/images/photography/passers-by/042_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/043.webp", thumb: "/images/photography/passers-by/043_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/044.webp", thumb: "/images/photography/passers-by/044_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/045.webp", thumb: "/images/photography/passers-by/045_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/passers-by/046.webp", thumb: "/images/photography/passers-by/046_thumb.webp", width: 1500, height: 1000 },
    ],
  },
  {
    slug: "cityscapes",
    title: "Cityscapes",
    images: [
      { src: "/images/photography/cityscapes/001.webp", thumb: "/images/photography/cityscapes/001_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/cityscapes/002.webp", thumb: "/images/photography/cityscapes/002_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/cityscapes/003.webp", thumb: "/images/photography/cityscapes/003_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/cityscapes/004.webp", thumb: "/images/photography/cityscapes/004_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/cityscapes/005.webp", thumb: "/images/photography/cityscapes/005_thumb.webp", width: 1500, height: 1000 },
    ],
  },
  {
    slug: "facades",
    title: "Facades",
    images: [
      { src: "/images/photography/facades/001.webp", thumb: "/images/photography/facades/001_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/002.webp", thumb: "/images/photography/facades/002_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/003.webp", thumb: "/images/photography/facades/003_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/004.webp", thumb: "/images/photography/facades/004_thumb.webp", width: 1500, height: 1125 },
      { src: "/images/photography/facades/005.webp", thumb: "/images/photography/facades/005_thumb.webp", width: 1500, height: 1124 },
      { src: "/images/photography/facades/006.webp", thumb: "/images/photography/facades/006_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/007.webp", thumb: "/images/photography/facades/007_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/008.webp", thumb: "/images/photography/facades/008_thumb.webp", width: 1500, height: 1125 },
      { src: "/images/photography/facades/009.webp", thumb: "/images/photography/facades/009_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/010.webp", thumb: "/images/photography/facades/010_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/011.webp", thumb: "/images/photography/facades/011_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/012.webp", thumb: "/images/photography/facades/012_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/013.webp", thumb: "/images/photography/facades/013_thumb.webp", width: 1500, height: 1125 },
      { src: "/images/photography/facades/014.webp", thumb: "/images/photography/facades/014_thumb.webp", width: 1500, height: 2000 },
      { src: "/images/photography/facades/015.webp", thumb: "/images/photography/facades/015_thumb.webp", width: 1500, height: 1125 },
      { src: "/images/photography/facades/016.webp", thumb: "/images/photography/facades/016_thumb.webp", width: 1500, height: 2000 },
    ],
  },
  {
    slug: "winter-in-boston",
    title: "Winter",
    images: [
      { src: "/images/photography/winter-in-boston/001.webp", thumb: "/images/photography/winter-in-boston/001_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/winter-in-boston/002.webp", thumb: "/images/photography/winter-in-boston/002_thumb.webp", width: 1500, height: 2250 },
      { src: "/images/photography/winter-in-boston/003.webp", thumb: "/images/photography/winter-in-boston/003_thumb.webp", width: 1500, height: 750 },
      { src: "/images/photography/winter-in-boston/004.webp", thumb: "/images/photography/winter-in-boston/004_thumb.webp", width: 1500, height: 1010 },
      { src: "/images/photography/winter-in-boston/005.webp", thumb: "/images/photography/winter-in-boston/005_thumb.webp", width: 1500, height: 2250 },
      { src: "/images/photography/winter-in-boston/006.webp", thumb: "/images/photography/winter-in-boston/006_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/winter-in-boston/007.webp", thumb: "/images/photography/winter-in-boston/007_thumb.webp", width: 1500, height: 750 },
      { src: "/images/photography/winter-in-boston/008.webp", thumb: "/images/photography/winter-in-boston/008_thumb.webp", width: 1500, height: 750 },
    ],
  },
  {
    slug: "frisco",
    title: "Frisco",
    images: [
      { src: "/images/photography/frisco/001.webp", thumb: "/images/photography/frisco/001_thumb.webp", width: 1500, height: 826 },
      { src: "/images/photography/frisco/002.webp", thumb: "/images/photography/frisco/002_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/frisco/003.webp", thumb: "/images/photography/frisco/003_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/frisco/004.webp", thumb: "/images/photography/frisco/004_thumb.webp", width: 1500, height: 750 },
      { src: "/images/photography/frisco/005.webp", thumb: "/images/photography/frisco/005_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/frisco/006.webp", thumb: "/images/photography/frisco/006_thumb.webp", width: 1365, height: 2048 },
      { src: "/images/photography/frisco/007.webp", thumb: "/images/photography/frisco/007_thumb.webp", width: 1500, height: 1000 },
      { src: "/images/photography/frisco/008.webp", thumb: "/images/photography/frisco/008_thumb.webp", width: 1280, height: 1920 },
      { src: "/images/photography/frisco/009.webp", thumb: "/images/photography/frisco/009_thumb.webp", width: 1365, height: 2048 },
    ],
  },
  {
    slug: "hong-kong",
    title: "Macau/Hong Kong",
    images: [
      { src: "/images/photography/hong-kong/001.webp", thumb: "/images/photography/hong-kong/001_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/002.webp", thumb: "/images/photography/hong-kong/002_thumb.webp", width: 1500, height: 1495 },
      { src: "/images/photography/hong-kong/003.webp", thumb: "/images/photography/hong-kong/003_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/004.webp", thumb: "/images/photography/hong-kong/004_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/005.webp", thumb: "/images/photography/hong-kong/005_thumb.webp", width: 1500, height: 1501 },
      { src: "/images/photography/hong-kong/006.webp", thumb: "/images/photography/hong-kong/006_thumb.webp", width: 1500, height: 1490 },
      { src: "/images/photography/hong-kong/007.webp", thumb: "/images/photography/hong-kong/007_thumb.webp", width: 1500, height: 1421 },
      { src: "/images/photography/hong-kong/008.webp", thumb: "/images/photography/hong-kong/008_thumb.webp", width: 1500, height: 1502 },
      { src: "/images/photography/hong-kong/009.webp", thumb: "/images/photography/hong-kong/009_thumb.webp", width: 1500, height: 1498 },
      { src: "/images/photography/hong-kong/010.webp", thumb: "/images/photography/hong-kong/010_thumb.webp", width: 1500, height: 1499 },
      { src: "/images/photography/hong-kong/011.webp", thumb: "/images/photography/hong-kong/011_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/012.webp", thumb: "/images/photography/hong-kong/012_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/013.webp", thumb: "/images/photography/hong-kong/013_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/014.webp", thumb: "/images/photography/hong-kong/014_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/015.webp", thumb: "/images/photography/hong-kong/015_thumb.webp", width: 1500, height: 1486 },
      { src: "/images/photography/hong-kong/016.webp", thumb: "/images/photography/hong-kong/016_thumb.webp", width: 1500, height: 1497 },
      { src: "/images/photography/hong-kong/017.webp", thumb: "/images/photography/hong-kong/017_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/018.webp", thumb: "/images/photography/hong-kong/018_thumb.webp", width: 1500, height: 1501 },
      { src: "/images/photography/hong-kong/019.webp", thumb: "/images/photography/hong-kong/019_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/020.webp", thumb: "/images/photography/hong-kong/020_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/021.webp", thumb: "/images/photography/hong-kong/021_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/022.webp", thumb: "/images/photography/hong-kong/022_thumb.webp", width: 1500, height: 1477 },
      { src: "/images/photography/hong-kong/023.webp", thumb: "/images/photography/hong-kong/023_thumb.webp", width: 1500, height: 1497 },
      { src: "/images/photography/hong-kong/024.webp", thumb: "/images/photography/hong-kong/024_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/025.webp", thumb: "/images/photography/hong-kong/025_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/026.webp", thumb: "/images/photography/hong-kong/026_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/027.webp", thumb: "/images/photography/hong-kong/027_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/028.webp", thumb: "/images/photography/hong-kong/028_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/029.webp", thumb: "/images/photography/hong-kong/029_thumb.webp", width: 1500, height: 1500 },
      { src: "/images/photography/hong-kong/030.webp", thumb: "/images/photography/hong-kong/030_thumb.webp", width: 1500, height: 1500 },
    ],
  },
  {
    slug: "robi",
    title: "Robi B",
    images: [
      { src: "/images/photography/robi/001.webp", thumb: "/images/photography/robi/001_thumb.webp", width: 1500, height: 1819 },
      { src: "/images/photography/robi/002.webp", thumb: "/images/photography/robi/002_thumb.webp", width: 1500, height: 1873 },
      { src: "/images/photography/robi/003.webp", thumb: "/images/photography/robi/003_thumb.webp", width: 1500, height: 1977 },
      { src: "/images/photography/robi/004.webp", thumb: "/images/photography/robi/004_thumb.webp", width: 1500, height: 1896 },
      { src: "/images/photography/robi/005.webp", thumb: "/images/photography/robi/005_thumb.webp", width: 1500, height: 1888 },
      { src: "/images/photography/robi/006.webp", thumb: "/images/photography/robi/006_thumb.webp", width: 1500, height: 1194 },
      { src: "/images/photography/robi/007.webp", thumb: "/images/photography/robi/007_thumb.webp", width: 1500, height: 1899 },
      { src: "/images/photography/robi/008.webp", thumb: "/images/photography/robi/008_thumb.webp", width: 1500, height: 1914 },
      { src: "/images/photography/robi/009.webp", thumb: "/images/photography/robi/009_thumb.webp", width: 1500, height: 1924 },
      { src: "/images/photography/robi/010.webp", thumb: "/images/photography/robi/010_thumb.webp", width: 1500, height: 1874 },
      { src: "/images/photography/robi/011.webp", thumb: "/images/photography/robi/011_thumb.webp", width: 1500, height: 2034 },
      { src: "/images/photography/robi/012.webp", thumb: "/images/photography/robi/012_thumb.webp", width: 1500, height: 1867 },
      { src: "/images/photography/robi/013.webp", thumb: "/images/photography/robi/013_thumb.webp", width: 1500, height: 1110 },
    ],
  },
];
