export let projects = [
    {
        "title": "Improved Distribution Matching Distillation for Fast Image Synthesis",
        "authors": [
            "Tianwei Yin",
            "Michaël Gharbi",
            "Taesung Park",
            "Richard Zhang",
            "Eli Shechtman",
            "Frédo Durand",
            "William T. Freeman",
        ],
        "venue": "NeurIPS",
        "year": "2024",
        "homepage": "https://tianweiy.github.io/dmd2/",
        "code": "https://github.com/tianweiy/DMD2",
        "pdf": "https://arxiv.org/abs/2405.14867",
        "image": ""
    },
    {
        "title": "One-step Diffusion with Distribution Matching Distillation",
        "authors": ["Tianwei Yin", "Michaël Gharbi", "Richard Zhang", "Eli Shechtman", "Frédo Durand", "William T. Freeman", "Taesung Park"],
        "venue": "CVPR",
        "year": "2024",
        "homepage": "https://tianweiy.github.io/dmd/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2311.18828",
        "image": ""
    },
    {
        "title": "Magic Fixup: Streamlining Photo Editing by Watching Dynamic Videos",
        "authors": [
            "Hadi Alzayer",
            "Zhihao Xia",
            "Xuaner (Cecilia) Zhang",
            "Eli Shechtman",
            "Jia-Bin Huang",
            "Michaël Gharbi",
        ],
        "venue": "arXiv",
        "year": "2024",
        "homepage": "https://magic-fixup.github.io/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2403.13044",
        "image": "",
    },
    {
        "title": "Lazy Diffusion Transformer for Interactive Image Editing",
        "authors": [
            "Yotam Nitzan",
            "Zongze Wu",
            "Richard Zhang",
            "Eli Shechtman",
            "Daniel Cohen-Or",
            "Taesung Park",
            "Michaël Gharbi",
        ],
        "venue": "ECCV",
        "year": "2024",
        "homepage": "https://lazydiffusion.github.io/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2404.12382",
        "image": ""
    },
    {
        "title": "Editable Image Elements for Controllable Synthesis",
        "authors": [
            "Jiteng Mu",
            "Michaël Gharbi",
            "Richard Zhang",
            "Eli Shechtman",
            "Nuno Vasconcelos",
            "Xiaolong Wang",
            "Taesung Park",
        ],
        "venue": "ECCV",
        "year": "2024",
        "homepage": "https://jitengmu.github.io/Editable_Image_Elements/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2404.16029",
        "image": ""
    },
    {
        "title": "Image Neural Field Diffusion Models",
        "authors": [
            "Yinbo Chen",
            "Oliver Wang",
            "Richard Zhang",
            "Eli Shechtman",
            "Xiaolong Wang",
            "Michaël Gharbi",
        ],
        "venue": "CVPR",
        "year": "2024 (highlight)",
        "homepage": "https://yinboc.github.io/infd/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2406.07480",
        "image": ""
    },
    {
        "title": "VecFusion: Vector Font Generation with Diffusion",
        "authors": [
            "Vikas Thamizharasan",
            "Difan Liu",
            "Shantanu Agarwal",
            "Matthew Fisher",
            "Michaël Gharbi",
            "Oliver Wang",
            "Alec Jacobson",
            "Evangelos Kalogerakis",
        ],
        "venue": "CVPR",
        "year": "2024",
        "homepage": "",
        "code": "",
        "pdf": "https://arxiv.org/abs/2312.10540",
        "image": ""
    },
    {
        "title": "Learning Subject-Aware Cropping by Outpainting Professional Photos",
        "authors": [
            "James Hong",
            "Lu Yuan",
            "Michaël Gharbi",
            "Matthew Fisher",
            "Kayvon Fatahalian",
        ],
        "venue": "AAAI",
        "year": "2024",
        "homepage": "https://jhong93.github.io/projects/crop.html",
        "code": "https://github.com/jhong93/gencrop",
        "pdf": "https://jhong93.github.io/pdf/crop-aaai24.pdf",
        "image": ""
    },
    {
        "title": "Discontinuity-Aware 2D Neural Fields",
        "authors": [
            "Yash Belhe",
            "Michaël Gharbi",
            "Matthew Fisher",
            "Iliyan Georgiev",
            "Ravi Ramamoorthi",
            "Tzu-Mao Li",
        ],
        "venue": "Siggraph Asia",
        "year": "2023",
        "homepage": "https://yashbelhe.github.io/danf/index.html",
        "code": "",
        "pdf": "https://yashbelhe.github.io/danf/DiscontinuityAwareNeuralFields_SigAsia2023.pdf",
        "image": ""
    },
    {
        "title": "Shadow Harmonization for Realistic Compositing",
        "authors": [
            "Luca Valença",
            "Jinsong Zhang",
            "Michaël Gharbi",
            "Yannick Hold-Geoffroy",
            "Jean-François Lalonde",
        ],
        "venue": "Siggraph Asia",
        "year": "2023",
        "homepage": "https://lvsn.github.io/shadowcompositing",
        "code": "",
        "pdf": "https://valenca.io/media/external/sa23/valenca2023shadow_compressed.pdf",
        "image": ""
    },
    {
        "title": "Self-Supervised Burst Super-Resolution",
        "authors": [
           "Goutam Bhat",
           "Michaël Gharbi",
           "Jiawen Chen",
           "Luc Van Gool",
           "Zhihao Xia",
        ],
        "venue": "ICCV",
        "year": "2023",
        "homepage": "",
        "code": "",
        "pdf": "https://openaccess.thecvf.com/content/ICCV2023/papers/Bhat_Self-Supervised_Burst_Super-Resolution_ICCV_2023_paper.pdf",
        "image": ""
    },
    {
        "title": "Materialistic: Selecting Similar Materials in Images",
        "authors": [
           "Prafull Sharma",
           "Julien Philip",
           "Michaël Gharbi",
           "William T. Freeman",
           "Frédo Durand",
           "Valentin Deschaintre",
        ],
        "venue": "Siggraph",
        "year": "2023",
        "homepage": "https://prafullsharma.net/materialistic/",
        "code": "",
        "pdf": "https://prafullsharma.net/materialistic/materialistic_camera_ready.pdf",
        "image": ""
    },
    {
        "title": "Domain Expansion of Image Generators",
        "authors": [
           "Yotam Nitzan",
           "Michaël Gharbi",
           "Richard Zhang",
           "Taesung Park",
           "Jun-Yan Zhu",
           "Daniel Cohen-Or",
           "Eli Shechtman",
        ],
        "venue": "CVPR",
        "year": "2023",
        "homepage": "https://yotamnitzan.github.io/domain-expansion/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2301.05225",
        "image": ""
    },
    {
        "title": "Semi-supervised Parametric Real-world Image Harmonization",
        "authors": [
            "Ke Wang",
            "Michaël Gharbi",
            "He Zhang",
            "Zhihao Xia",
            "Eli Shechtman",
        ],
        "venue": "CVPR",
        "year": "2023",
        "homepage": "https://kewang0622.github.io/sprih/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2303.00157",
        "image": ""
    },
    {
        "title": "Differentiable Rendering of Neural SDFs through Reparameterization",
        "authors": [
            "Sai Praveen Bangaru",
            "Michaël Gharbi",
            "Tzu-Mao Li",
            "Fujun Luan",
            "Kalyan Sunkavalli",
            "Milos Hasan",
            "Sai Bi",
            "Zexiang Xu",
            "Gilbert Bernstein",
            "Frédo Durand",
        ],
        "venue": "Siggraph Asia",
        "year": "2022",
        "homepage": "http://people.csail.mit.edu/sbangaru/projects/dsdf-2022/index.html",
        "code": "",
        "pdf": "http://people.csail.mit.edu/sbangaru/projects/dsdf-2022/dsdf-2022.pdf",
        "image": ""
    },
    {
        "title": "Any-resolution Training for High-resolution Image Synthesis",
        "authors": [
            "Lucy Chai",
            "Michaël Gharbi",
            "Eli Shechtman",
            "Phillip Isola",
            "Richard Zhang",
                
        ],
        "venue": "ECCV",
        "year": "2022",
        "homepage": "https://chail.github.io/anyres-gan/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2204.07156",
        "image": ""
    },
    {
        "title": "Spotting Temporally Precise, Fine-Grained Events in Video",
        "authors": [
            "James Hong",
            "Haotian Zhang",
            "Michaël Gharbi",
            "Matthew Fisher",
            "Kayvon Fatahalian",
                
        ],
        "venue": "ECCV",
        "year": "2022",
        "homepage": "https://jhong93.github.io/projects/spot.html",
        "code": "",
        "pdf": "https://jhong93.github.io/pdf/spot-eccv22.pdf",
        "image": ""
    },
    {
        "title": "Searching for Fast Demosaicking Algorithms",
        "authors": [
            "Karima Ma",
            "Michaël Gharbi",
            "Andrew Adams",
            "Shoaib Kamil",
            "Tzu-Mao Li",
            "Connelly Barnes",
            "Jonathan Ragan-Kelley",
        ],
        "venue": "Siggraph (ToG)",
        "year": "2022",
        "homepage": "http://people.csail.mit.edu/karima/searching_for_fast_demosaicking_algorithms.pdf",
        "code": "",
        "pdf": "",
        "image": ""
    },
    {
        "title": "Free-viewpoint Indoor Neural Relighting from Multi-view Stereo",
        "authors": [
            "Julien Philip",
            "Sébastien Morgenthaler",
            "Michaël Gharbi",
            "George Drettaki",
        ],
        "venue": "Siggraph (ToG)",
        "year": "2022",
        "homepage": "http://www-sop.inria.fr/reves/Basilic/2021/PMGD21/",
        "code": "",
        "pdf": "http://www-sop.inria.fr/reves/Basilic/2021/PMGD21/PhilipFreeViewPointIndoorRelighting.pdf",
        "image": ""
    },
    {
        "title": "Interactive Monte Carlo Denoising using Affinity of Neural Features",
        "authors": [
            "Mustafa Işık",
            "Krishna Mullia",
            "Matthew Fisher",
            "Jonathan Eisenmann",
            "Michaël Gharbi",
        ],
        "venue": "Siggraph",
        "year": "2021",
        "homepage": "https://www.mustafaisik.net/anf/",
        "code": "",
        "pdf": "https://www.mustafaisik.net/pdfs/isik2021-anf.pdf",
        "image": ""
    },
    {
        "title": "MarioNette: Self-Supervised Sprite Learning",
        "authors": [
            "Dmitriy Smirnov",
            "Michaël Gharbi",
            "Matthew Fisher",
            "Vitor Guizilini",
            "Alexei A. Efros",
            "Justin Solomon",
        ],
        "venue": "NeurIPS",
        "year": "2021",
        "homepage": "https://people.csail.mit.edu/smirnov/marionette/",
        "code": "",
        "pdf": "https://arxiv.org/pdf/2104.14553.pdf",
        "image": ""
    },
    {
        "title": "Modulated Periodic Activations for Generalizable Local Functional Representations",
        "authors": [
            "Ishit Mehta",
            "Michaël Gharbi",
            "Connelly Barnes",
            "Eli Shechtman",
            "Ravi Ramamoorthi",
            "Manmohan Chandraker",
        ],
        "venue": "ICCV",
        "year": "2021",
        "homepage": "https://ishit.github.io/modsine/",
        "code": "",
        "pdf": "https://arxiv.org/pdf/2104.03960.pdf",
        "image": ""
    },
    {
        "title": "Video Pose Distillation for Few-Shot, Fine-Grained Sports Action Recognition",
        "authors": [
            "James Hong",
            "Matthew Fisher",
            "Michaël Gharbi",
            "Kayvon Fatahalian",
        ],
        "venue": "ICCV",
        "year": "2021",
        "homepage": "https://jhong93.github.io/projects/vpd.html",
        "code": "",
        "pdf": "https://arxiv.org/abs/2109.01305",
        "image": ""
    },
    {
        "title": "Im2Vec: Synthesizing Vector Graphics without Vector Supervision",
        "authors": [
            "Pradyumna Reddy",
            "Michaël Gharbi",
            "Michal Lukáč",
            "Niloy J. Mitra",
        ],
        "venue": "CVPR",
        "year": "2021",
        "homepage": "http://geometry.cs.ucl.ac.uk/projects/2021/im2vec/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2102.02798",
        "image": ""
    },
    {
        "title": "Spatially-Adaptive Pixelwise Networks for Fast Image Translation",
        "authors": [
            "Tamar Rott Shaham",
            "Michaël Gharbi",
            "Richard Zhang",
            "Eli Shechtman",
            "Tomer Michaeli",
        ],
        "venue": "CVPR",
        "year": "2021",
        "homepage": "https://tamarott.github.io/ASAPNet_web/",
        "code": "",
        "pdf": "https://arxiv.org/pdf/2012.02992.pdf",
        "image": ""
    },
    {
        "title": "Deep Denoising of Flash and No-Flash Pairs for Photography in Low-Light Environments",
        "authors": [
           "Zhihao Xia",
           "Michaël Gharbi",
           "Federico Perazzi",
           "Kalyan Sunkavalli",
           "Ayan Chakrabarti",
        ],
        "venue": "CVPR",
        "year": "2021",
        "homepage": "https://www.cse.wustl.edu/~zhihao.xia/deepfnf/",
        "code": "",
        "pdf": "https://arxiv.org/abs/2012.05116",
        "image": ""
    },
    {
        "title": "Differentiable Vector Graphics Rasterization for Editing and Learning",
        "authors": [
            "Tzu-Mao Li",
            "Michal Lukáč",
            "Michaël Gharbi",
            "Jonathan Ragan-Kelley",
        ],
        "venue": "Siggraph Asia",
        "year": "2020",
        "homepage": "https://people.csail.mit.edu/tzumao/diffvg/",
        "code": "https://github.com/BachiLi/diffvg",
        "pdf": "https://people.csail.mit.edu/tzumao/diffvg/diffvg.pdf",
        "image": ""
    },
    {
        "title": "Basis Prediction Networks for Effective Burst Denoising with Large Kernels",
        "authors": [
            "Zhihao Xia",
            "Federico Perazzi",
            "Michaël Gharbi",
            "Kalyan Sunkavalli",
            "Ayan Chakrabarti",
        ],
        "venue": "CVPR",
        "year": "2020",
        "homepage": "https://likesum.github.io/bpn",
        "code": "https://github.com/likesum/bpn",
        "pdf": "https://arxiv.org/pdf/1912.04421.pdf",
        "image": ""
    },
    {
        "title": "A Dataset of Multi-Illumination Images in the Wild",
        "authors": [
            "Lukas Murmann",
            "Michaël Gharbi",
            "Miika Aittala",
            "Frédo Durand",
        ],
        "venue": "ICCV",
        "year": "2019",
        "homepage": "https://projects.csail.mit.edu/illumination/",
        "code": "https://github.com/lmurmann/multi_illumination",
        "pdf": "https://arxiv.org/pdf/1910.08131.pdf",
        "image": ""
    },
    {
        "title": "Sample-based Monte Carlo Denoising using a Kernel-Splatting Network",
        "authors": [
            "Michaël Gharbi",
            "Tzu-Mao Li",
            "Miika Aittala",
            "Jaakko Lehtinen",
            "Frédo Durand",
        ],
        "venue": "Siggraph",
        "year": "2019",
        "homepage": "http://groups.csail.mit.edu/graphics/rendernet/",
        "code": "https://github.com/adobe/sbmc",
        "pdf": "http://groups.csail.mit.edu/graphics/rendernet/data/mc_denoising.pdf",
        "image": ""
    },
    {
        "title": "Multi-view Relighting using a Geometry-Aware Network",
        "authors": [
            "Julien Philip",
            "Michaël Gharbi",
            "Tinghui Zhou",
            "Alexei A. Efros",
            "George Drettakis",
        ],
        "venue": "Siggraph",
        "year": "2019",
        "homepage": "https://repo-sam.inria.fr/fungraph/deep-relighting/",
        "code": "",
        "pdf": "https://repo-sam.inria.fr/fungraph/deep-relighting/Multi-view-Relighting.pdf",
        "image": ""
    },
    {
        "title": "Learning to Optimize Halide with Tree Search and Random Programs",
        "authors": [
            "Andrew Adams",
            "Karima Ma",
            "Luke Anderson",
            "Riyadh Baghdadi",
            "Tzu-Mao Li",
            "Michaël Gharbi",
            "Benoit Steiner",
            "Steven Johnson",
            "Kayvon Fatahalian",
            "Frédo Durand",
            "Jonathan Ragan-Kelley",
        ],
        "venue": "Siggraph",
        "year": "2019",
        "homepage": "https://halide-lang.org/papers/autoscheduler2019.html",
        "code": "https://github.com/halide/Halide/tree/main/src/autoschedulers/adams2019",
        "pdf": "https://halide-lang.org/papers/halide_autoscheduler_2019.pdf",
        "image": ""
    },
    {
        "title": "Learning Efficient Image Processing Pipelines",
        "authors": [
            "Michaël Gharbi",
        ],
        "venue": "MIT PhD Thesis",
        "year": "2018",
        "homepage": "",
        "code": "",
        "pdf": "data/gharbi_thesis_small.pdf",
        "image": ""
    },
    {
        "title": "Differentiable Programming for Image Processing and Deep Learning in Halide",
        "authors": [
            "Tzu-Mao Li",
            "Michaël Gharbi",
            "Andrew Adams",
            "Frédo Durand",
            "Jonathan Ragan-Kelley"
        ],
        "venue": "Siggraph",
        "year": "2018",
        "homepage": "https://people.csail.mit.edu/tzumao/gradient_halide/",
        "code": "https://github.com/halide/Halide",
        "pdf": "https://people.csail.mit.edu/tzumao/gradient_halide/gradient_halide.pdf",
        "image": ""
    },
    {
        "title": "Convolutional Neural Network for Earthquake Detection and Location",
        "authors": [
            "Thibaut Perol",
            "Micha&euml;l Gharbi",
            "Marine Denolle",
        ],
        "venue": "Science Advances",
        "year": "2018",
        "homepage": "https://groups.csail.mit.edu/graphics/convnetquake/",
        "code": "https://github.com/tperol/ConvNetQuake",
        "pdf": "http://advances.sciencemag.org/content/4/2/e1700578/tab-pdf",
        "image": ""
    },
    {
        "title": "Deep Bilateral Learning for Real-Time Image Enhancement",
        "authors": [
            "Michaël Gharbi",
            "Jiawen Chen",
            "Jonathan T. Barron",
            "Samuel W. Hasinoff",
            "Frédo Durand",
        ],
        "venue": "Siggraph",
        "year": "2017",
        "homepage": "https://groups.csail.mit.edu/graphics/hdrnet/",
        "code": "https://github.com/mgharbi/hdrnet",
        "pdf": "https://groups.csail.mit.edu/graphics/hdrnet/data/hdrnet.pdf",
        "image": ""
    },
    {
        "title": "Deep Joint Demosaicking and Denoising",
        "authors": [
           "Michaël Gharbi",
           "Gaurav Chaurasia",
           "Sylvain Paris",
           "Frédo Durand",
        ],
        "venue": "Siggraph Asia",
        "year": "2016",
        "homepage": "https://groups.csail.mit.edu/graphics/demosaicnet/",
        "code": "https://github.com/mgharbi/demosaicnet",
        "pdf": "https://groups.csail.mit.edu/graphics/demosaicnet/data/demosaic.pdf",
        "image": ""
    },
    {
        "title": "Transform Recipes for Efficient Cloud Photo Enhancement",
        "authors": [
            "Michaël Gharbi",
            "YiChang Shih",
            "Gaurav Chaurasia",
            "Jonathan Ragan-Kelley",
            "Sylvain Paris",
            "Frédo Durand",
        ],
        "venue": "Siggraph Asia",
        "year": "2015",
        "homepage": "https://groups.csail.mit.edu/graphics/xform_recipes/",
        "code": "https://github.com/mgharbi/xform_recipes",
        "pdf": "https://groups.csail.mit.edu/graphics/xform_recipes/data/xform_paper_sigasia2015.pdf",
        "image": ""
    },
    {
        "title": "A Gaussian Approximation of Feature Space for Fast Image Similarity",
        "authors": [
            "Michaël Gharbi",
            "Tomasz Malisiewicz",
            "Sylvain Paris",
            "Frédo Durand"
        ],
        "venue": "MIT Technical Report",
        "year": "2012",
        "homepage": "https://groups.csail.mit.edu/graphics/gaussian_approximation/",
        "code": "",
        "pdf": "http://dspace.mit.edu/bitstream/handle/1721.1/73685/MIT-CSAIL-TR-2012-032.pdf?sequence=1",
        "image": ""
    },
];
